[package]
name = "elfreader"
version = "0.1.0"
authors = ["fluffyChaos <maskedFluffyPanda@protonmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitflags = "1.3.2"